sudo apt-get -y update
sudo apt-get -y upgrade

sudo apt-get -y bc
sudo apt-get -y bison
sudo apt-get -y build-essential
sudo apt-get -y ccache
sudo apt-get -y curl
sudo apt-get -y flex
sudo apt-get -y g++-multilib
sudo apt-get -y gcc-multilib
sudo apt-get -y git
sudo apt-get -y git-lfs
sudo apt-get -y gnupg
sudo apt-get -y gperf
sudo apt-get -y imagemagick
sudo apt-get -y lib32ncurses5-dev
sudo apt-get -y lib32readline-dev
sudo apt-get -y lib32z1-dev
sudo apt-get -y libelf-dev
sudo apt-get -y liblz4-tool
sudo apt-get -y libncurses5
sudo apt-get -y libncurses5-dev
sudo apt-get -y libsdl1.2-dev
sudo apt-get -y libssl-dev
sudo apt-get -y libxml2
sudo apt-get -y libxml2-utils
sudo apt-get -y lzop
sudo apt-get -y pngcrush
sudo apt-get -y rsync
sudo apt-get -y schedtool
sudo apt-get -y squashfs-tools
sudo apt-get -y xsltproc
sudo apt-get -y zip
sudo apt-get -y zlib1g-dev
