sudo apt remove moby-buildx
sudo apt remove moby-cli
sudo apt remove moby-compose
sudo apt remove moby-containerd
sudo apt remove moby-engine
sudo apt remove moby-runc
sudo apt remove podman buildah
sudo apt remove skopeo
sudo apt remove containers-common
sudo apt remove temurin-*-jdk
sudo apt remove adoptopenjdk-*
sudo apt remove adoptium-ca-certificates
sudo apt remove openjdk-*
sudo apt remove ant
sudo apt remove ant-optional
sudo apt remove postgresql-*
sudo apt remove libpq-dev
sudo apt remove libmysqlclient*
sudo apt remove msodbcsql* mssql-tools
sudo apt remove unixodbc-dev
sudo apt remove mysql-client*
sudo apt remove mysql-common
sudo apt remove mysql-server*
sudo apt remove php*-*sql
sudo apt remove sphinxsearch
sudo apt remove mongodb*
sudo apt remove firefox
sudo apt remove google-chrome-stable
sudo apt remove microsoft-edge-stable
sudo apt remove xvfb
sudo apt remove apache2
sudo apt remove apache2-*
sudo apt remove nginx nginx-*
sudo apt remove php-*
sudo apt remove php7*
sudo apt remove php8*
sudo apt remove session-manager-plugin
sudo apt remove azure-cli
sudo apt remove google-cloud-sdk
sudo apt remove gh
sudo apt remove subversion
sudo apt remove mercurial
sudo apt remove vim
sudo apt remove vim-*
sudo apt remove dotnet*
sudo apt remove aspnetcore*
sudo apt remove mono-*
sudo apt remove mono*
sudo apt remove libmono-*
sudo apt remove libmono*
sudo apt remove monodoc*
sudo apt remove msbuild
sudo apt remove nuget
sudo apt remove ruby*
sudo apt remove rake
sudo apt remove ri
sudo apt remove g++-10
sudo apt remove g++-12
sudo apt remove gcc-10
sudo apt remove gcc-12
sudo apt remove gfortran-*
sudo apt remove clang-*
sudo apt remove libclang*
sudo apt remove llvm-*
sudo apt remove libllvm*
sudo apt remove lldb-*
sudo apt remove lld-*
sudo apt remove clang-format-*
sudo apt remove clang-tidy-*
sudo apt remove powershell
sudo apt remove r-base*
sudo apt remove r-cran*
sudo apt remove r-doc*
sudo apt remove r-recommended
sudo apt remove snapd
sudo apt remove man-db
sudo apt remove manpages
sudo apt remove libgtk-3-*
sudo apt remove ubuntu-mono
sudo apt remove *-icon-theme
sudo apt remove esl-erlang
sudo apt remove imagemagick
sudo apt remove imagemagick-6-common
sudo apt remove libgl1-mesa-dri
sudo apt remove firebird*
sudo apt remove hhvm
sudo apt remove python
sudo apt remove python2

sudo rm -rf /home/linuxbrew
sudo rm -rf /usr/bin/docker-credential-ecr-login
sudo rm -rf /usr/local/bin/docker-compose
sudo rm -rf /usr/bin/docker-credential-ecr-login
sudo rm -rf /usr/local/bin/kind
sudo rm -rf /usr/local/bin/kubectl
sudo rm -rf /usr/local/bin/minikube
sudo rm -rf /usr/local/bin/kustomize
sudo rm -rf /usr/local/bin/helm
sudo rm -rf /usr/local/bin/terraform
sudo rm -rf /usr/local/lib/android/sdk/build-tools
sudo rm -rf /usr/local/lib/android/sdk/cmdline-tools
sudo rm -rf /usr/local/lib/android/sdk/cmake
sudo rm -rf /usr/local/lib/android/sdk/emulator
sudo rm -rf /usr/local/lib/android/sdk/licenses
sudo rm -rf /usr/local/lib/android/sdk/extras
sudo rm -rf /usr/local/lib/android/sdk/ndk
sudo rm -rf /usr/local/lib/android/sdk/patcher
sudo rm -rf /usr/local/lib/android/sdk/platform-tools
sudo rm -rf /usr/local/lib/android/sdk/tools
sudo rm -rf /usr/local/lib/android/sdk/platforms
sudo rm -rf /usr/local/lib/android
sudo rm -rf /usr/lib/jvm/
sudo rm -rf /usr/local/graalvm
sudo rm -rf /usr/share/java/selenium-server.jar
sudo rm -rf /usr/share/gradle-8.0.2
sudo rm -rf /usr/bin/gradle
sudo rm -rf /usr/share/apache-maven-3.8.8
sudo rm -rf /usr/bin/mvn
sudo rm -rf /usr/share/mysql\*
sudo rm -rf /opt/mssql-tools
sudo rm -rf /usr/lib/firefox
sudo rm -rf /usr/local/sqlpackage
sudo rm -rf /usr/local/share/gecko_driver
sudo rm -rf /usr/bin/google-chrome
sudo rm -rf /usr/bin/geckodriver
sudo rm -rf /usr/local/share/chrome_driver
sudo rm -rf /usr/bin/chromedriver
sudo rm -rf /usr/local/share/chromium
sudo rm -rf /usr/bin/chromium-browser
sudo rm -rf /usr/bin/chromium
sudo rm -rf /usr/local/share/edge_driver
sudo rm -rf /usr/bin/msedgedriver
sudo rm -rf /usr/share/php
sudo rm -rf /etc/php
sudo rm -rf /usr/local/bin/phpunit
sudo rm -rf /usr/bin/composer
sudo rm -rf /home/runner/.config/composer
sudo rm -rf /etc/.composer
sudo rm -rf /etc/skel/.composer
sudo rm -rf /usr/local/bin/aliyun
sudo rm -rf /usr/local/bin/aws
sudo rm -rf /usr/local/bin/aws_completer
sudo rm -rf /usr/local/aws
sudo rm -rf /usr/local/aws-cli
sudo rm -rf /usr/local/bin/azcopy
sudo rm -rf /usr/local/bin/azcopy10
sudo rm -rf /usr/share/az_3.1.0.zip
sudo rm -rf /usr/share/az_4.4.0.zip
sudo rm -rf /usr/share/az_5.9.0.zip
sudo rm -rf /usr/share/az_6.6.0.zip
sudo rm -rf /usr/share/az_7.5.0.zip
sudo rm -rf /usr/share/az_9.3.0
sudo rm -rf /opt/az
sudo rm -rf /usr/bin/az
sudo rm -rf /usr/share/google-cloud-sdk
sudo rm -rf /usr/local/bin/bicep
sudo rm -rf /usr/local/bin/oc
sudo rm -rf /usr/local/bin/oras
sudo rm -rf /usr/local/bin/hub
sudo rm -rf /usr/share/dotnet
sudo rm -rf /home/runner/.dotnet
sudo rm -rf /etc/skel/.dotnet/tools
sudo rm -rf /etc/.dotnet/tools
sudo rm -rf /usr/local/aws-sam-cli
sudo rm -rf /usr/local/bin/vcpkg
sudo rm -rf /usr/share/ri
sudo rm -rf /usr/local/n
sudo rm -rf /usr/local/bin/n
sudo rm -rf /usr/local/lib/node_modules
sudo rm -rf /etc/skel/.nvm
sudo rm -rf /home/runner/.nvm
sudo rm -rf /opt/pipx
sudo rm -rf /opt/pipx_bin
sudo rm -rf /opt/hostedtoolcache/CodeQL
sudo rm -rf /opt/hostedtoolcache/Java_Adopt_jdk
sudo rm -rf /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk
sudo rm -rf /opt/hostedtoolcache/PyPy
sudo rm -rf /opt/hostedtoolcache/Python
sudo rm -rf /opt/hostedtoolcache/Ruby
sudo rm -rf /usr/local/share/vcpkg
sudo rm -rf /opt/hostedtoolcache/node
sudo rm -rf /usr/lib/llvm-10
sudo rm -rf /usr/local/bin/ccmake
sudo rm -rf /usr/local/bin/cmake
sudo rm -rf /usr/local/bin/cmake-gui
sudo rm -rf /usr/local/bin/ctest
sudo rm -rf /usr/local/bin/cpack
sudo rm -rf /usr/local/share/cmake-3.26
sudo rm -rf /usr/local/\*cmake\*
sudo rm -rf /usr/local/bin/ccmake
sudo rm -rf /usr/local/bin/cmake
sudo rm -rf /usr/local/bin/cmake-gui
sudo rm -rf /opt/hostedtoolcache/go
sudo rm -rf /usr/local/doc/cmake
sudo rm -rf /usr/local/share/cmake-3.26
sudo rm -rf /opt/microsoft/powershell
sudo rm -rf /usr/share/rust
sudo rm -rf /home/runner/.cargo
sudo rm -rf /home/runner/.rustup
sudo rm -rf /etc/skel/.rustup
sudo rm -rf /etc/skel/.cargo
sudo rm -rf /etc/.rustup
sudo rm -rf /etc/.cargo
sudo rm -rf /usr/local/bin/stack
sudo rm -rf /home/runner/.ghcup
sudo rm -rf /usr/local/.ghcup
sudo rm -rf /usr/share/kotlinc
sudo rm -rf /usr/bin/kotlin
sudo rm -rf /usr/bin/kotlin-dce-js
sudo rm -rf /usr/local/share/powershell
sudo rm -rf /usr/bin/kotlinc
sudo rm -rf /usr/bin/kotlinc-js
sudo rm -rf /usr/bin/kotlinc-jvm
sudo rm -rf /usr/bin/julia
sudo rm -rf /usr/share/swift
sudo rm -rf /usr/local/bin/swift
sudo rm -rf /usr/local/bin/swiftc
sudo rm -rf /var/cache/snapd
sudo rm -rf /home/runner/snap
sudo rm -rf /usr/local/bin/rebar3
sudo rm -rf /usr/share/firebird\*
sudo rm -rf /opt/hhvm
sudo rm -rf /usr/share/sbt
sudo rm -rf /usr/bin/sbt
sudo rm -rf /usr/local/share/phantomjs-2.1.1-linux-x86_64
sudo rm -rf /usr/local/bin/phantomjs
sudo rm -rf /usr/local/bin/packer
sudo rm -rf /usr/local/lib/lein
sudo rm -rf /usr/local/bin/lein
sudo rm -rf /usr/local/bin/pulumi
sudo rm -rf /usr/local/bin/pulumi-analyzer-policy
sudo rm -rf /usr/local/bin/pulumi-analyzer-policy-python
sudo rm -rf /usr/local/bin/pulumi-language-dotnet
sudo rm -rf /usr/local/bin/pulumi-language-go
sudo rm -rf /usr/local/bin/pulumi-language-java
sudo rm -rf /usr/local/bin/pulumi-language-nodejs
sudo rm -rf /usr/local/bin/pulumi-language-python
sudo rm -rf /usr/local/bin/pulumi-language-python-exec
sudo rm -rf /usr/local/bin/pulumi-language-yaml
sudo rm -rf /usr/local/bin/pulumi-resource-pulumi-nodejs
sudo rm -rf /usr/local/bin/pulumi-resource-pulumi-python
sudo rm -rf /usr/local/bin/pulumi-watch
sudo rm -rf /usr/local/julia1.8.5
sudo rm -rf /usr/bin/conda
sudo rm -rf /usr/share/miniconda
sudo rm -rf /usr/share/dotnet
sudo rm -rf /opt/ghc
sudo rm -rf /usr/local/share/boost
sudo rm -rf "$AGENT_TOOLSDIRECTORY"

df -hT /home
