name: RedWolf-RP Builder
on:
  workflow_dispatch:
    inputs:
      MANIFEST_BRANCH:
        description: 'Manifest Branch'
        required: true
        default: 'rw-n'
        type: choice
        options:
          - 'rw'
          - 'rw-n'
      DEVICE_TREE_URL:
        description: 'Device Tree URL'
        required: true
        default: 'https://github.com/VThang51/android_device_samsung_a13'
      DEVICE_TREE_BRANCH:
        description: 'Device Tree Branch'
        required: true
        default: 'master'
      BRAND:
        description: 'Brand'
        required: true
        default: 'samsung'
      DEVICE_CODE:
        description: 'Device Code'
        required: true
        default: 'a13x'
      MAKEFILE_TYPE:
        description: 'Makefile Type'
        required: true
        default: 'twrp'
        type: choice
        options:
          - 'omni'
          - 'twrp'
      ADD_EXPORT:
        description: 'Add "export"'
        required: false
      BUILD_TARGET:
        description: 'Build Target'
        required: true
        default: 'recovery'
        type: choice
        options:
          - 'recovery'
          - 'boot'
          - 'vendorboot'
jobs:
  RedWolf-Recovery-Project:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Free up space
        run: bash sh/RP/unin.sh

      - name: Set up the Compilation environment
        run: bash sh/RP/sudo.sh

      - name: Git Config
        run: |
          rm -rf ~/rwrp
          mkdir ~/rwrp
          cd ~/rwrp
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
          
      - name: Sync Minimal Manifest
        run: |
          cd ~/rwrp
          repo init --depth=1 -u https://github.com/RedWolfRecovery/rw_manifest.git -b ${{ inputs.MANIFEST_BRANCH }}
          
      - name: Sync Source
        run: |
          cd ~/rwrp
          repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags
          rm -rf .rep
      
      - name: Clone Device Tree
        run: |
          cd ~/rwrp
          git clone -b ${{ inputs.DEVICE_TREE_BRANCH }} ${{ inputs.DEVICE_TREE_URL }} device/${{ inputs.BRAND }}/${{ inputs.DEVICE_CODE }}

      - name: Compile Custom Recovery 
        run: |
          cd ~/rwrp
          chmod 777 build/envsetup.sh
          export ALLOW_MISSING_DEPENDENCIES=true
          ${{ inputs.ADD_EXPORT }}
          . build/envsetup.sh
          lunch ${{ inputs.MAKEFILE_TYPE }}_${{ inputs.DEVICE_CODE }}-eng
          mka ${{ inputs.BUILD_TARGET }}image
        continue-on-error: true

      - name: Rename File
        run: |
          mv ~/rwrp/out/target/product/${{ inputs.DEVICE_CODE }}/${{ inputs.BUILD_TARGET }}.img UnofficialRedWolf-${{ inputs.DEVICE_CODE }}.img

      - name: Upload to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: UnofficialRedWolf-${{ inputs.DEVICE_CODE }}.img
          path: /home/runner/work/ROM_Recovery-Builder/ROM_Recovery-Builder/UnofficialRedWolf-${{ inputs.DEVICE_CODE }}.img
